version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      memory: 512M
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped